import combinatorial_structures_finite_projective_spaces_theorem_canonical_lane_mathlib.GateLemmas
import combinatorial_structures_finite_projective_spaces_theorem_canonical_lane_mathlib.FinalTheorem
